// Route-side wire contracts for the cloud auto-layout service
// (cloud-auto-layout, /v1/route, port 3002 — formerly the standalone cloud-auto-router).
//
// THESE ARE NO LONGER HAND-WRITTEN. Every shape below is an alias of a type generated
// from the service's emitted JSON Schema (./cloud-autolayout, generated by
// `npm run gen:contracts` from src/sdks/designer/contracts/*.schema.json). This module
// survives only as the stable import surface the desktop already uses — new code should
// import from ./cloud-autolayout directly.
//
// Hand-mirroring is what this replaces: the previous version of this file tracked six
// documented gaps against the schema (constraintGroups, placement metadata, subset
// placement, 9 of 15 place weights, …) and silently grew more with every service release.
//
// Units (load-bearing, unchanged): `traces[].pointsNm` and operation trace `pointsNm` are
// integer NANOMETERS; every other coordinate/dimension is MILLIMETERS (mm).

import type {
  JobStatusResponse,
  ProgressFrameRoute,
  RouteResultEnvelope as GeneratedRouteResultEnvelope,
} from "./cloud-autolayout";

// ── BoardSnapshot (request) ──────────────────────────────────────────────

export type {
  BoardGeometry,
  BoardSnapshot,
  ConstraintGroup,
  ExistingTrace,
  FreeHole,
  PadOutline,
  PlaceOptions,
  PlaceWeights,
  PointNm,
  PourIsland,
  RatsnestTarget,
  RouteOptions,
  Stackup,
  ViaObstacle,
  // Desktop policy narrowing (2/4-layer cloud contract), not a service shape.
  SnapshotCopperLayerId,
  SnapshotLayerCount,
} from "./cloud-autolayout";

import type {
  DesignRules,
  NetClass,
  Placement,
  RouteOptions as GeneratedRouteOptions,
} from "./cloud-autolayout";

/** Design rules as the service consumes them. */
export type SnapshotDesignRules = DesignRules;
/** Net class as the service consumes it. */
export type SnapshotNetClass = NetClass;
/** One placed component, including the metadata the placer reads. */
export type SnapshotPlacement = Placement;
/** Per-layer preferred routing axis, or "auto" for neutral. */
export type LayerPolicy = NonNullable<GeneratedRouteOptions["layerPolicy"]>;

// ── RouteResultEnvelope (response) ───────────────────────────────────────

export type {
  NetRouteStats,
  RouteCompletion,
  RouteDeterminism,
  RouteMetrics,
  RouteOperation,
  RoutePayloadSummary,
  RouteResultEnvelope,
  UnroutedNet,
  VariantStats,
} from "./cloud-autolayout";

import type { RouteOperation } from "./cloud-autolayout";

export type AutorouteRiskLevel = RouteOperation["riskLevel"];
export type RouteOperationKind = RouteOperation["kind"];
/** The op body — already a valid desktop designer command (carries `type`). */
export type RouteOperationPayload = RouteOperation["payload"];
export type UnroutedReason =
  import("./cloud-autolayout").UnroutedNet["reason"];

// ── Async job wire shapes ────────────────────────────────────────────────

export type { SubmitJobResponse as SubmitRouteResponse } from "./cloud-autolayout";

/** Job-record status from `GET /v1/route/{id}` (distinct from ProgressFrame.type). */
export type RouteJobStatus = NonNullable<JobStatusResponse["status"]>;

/** `GET /v1/route/{id}` with `result` narrowed to the route envelope. */
export interface RouteStatusResponse
  extends Omit<JobStatusResponse, "result" | "status"> {
  status: RouteJobStatus;
  result: GeneratedRouteResultEnvelope | null;
}

/**
 * Route progress frame types.
 *
 * Treat an unrecognized value as an ignorable progress tick rather than an error: the
 * service can add frame types without a desktop release (portfolio-variant frames, for
 * one, are emitted by the engine but not yet declared in the contract).
 */
export type ProgressFrameType = ProgressFrameRoute["type"];
export type ProgressFrame = ProgressFrameRoute;

// ── /v1/version ──────────────────────────────────────────────────────────

export type { VersionResponse } from "./cloud-autolayout";
