// AUTO-GENERATED by scripts/gen-copilot-tool-schemas.ts — do not edit.
// Runtime map of cloud-copilot tool JSON schemas (keyed by schema name), vendored
// from @openpcb/contracts/schemas/copilot. remoteTool() resolves a manifest
// entry's inputSchemaRef against this map. Regenerate: npm run gen:copilot-schemas.
import type { AiJsonSchemaObject } from "@openpcb/ai-core";

export const COPILOT_TOOL_SCHEMAS = {
  "BlobStatusResponse": {
    "properties": {
      "sha256": {
        "title": "Sha256",
        "type": "string"
      },
      "status": {
        "enum": [
          "registered",
          "queued",
          "fetching",
          "extracting",
          "embedding",
          "done",
          "failed"
        ],
        "title": "Status",
        "type": "string"
      },
      "pageCount": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Pagecount"
      },
      "ocrUsed": {
        "default": false,
        "title": "Ocrused",
        "type": "boolean"
      },
      "lang": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Lang"
      },
      "attempts": {
        "default": 0,
        "title": "Attempts",
        "type": "integer"
      },
      "failureReason": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Failurereason"
      }
    },
    "required": [
      "sha256",
      "status"
    ],
    "title": "BlobStatusResponse",
    "type": "object"
  },
  "ComponentSearchRequest": {
    "properties": {
      "query": {
        "maxLength": 500,
        "minLength": 1,
        "title": "Query",
        "type": "string"
      },
      "count": {
        "default": 10,
        "maximum": 20,
        "minimum": 1,
        "title": "Count",
        "type": "integer"
      }
    },
    "required": [
      "query"
    ],
    "title": "ComponentSearchRequest",
    "type": "object"
  },
  "ComponentSearchResponse": {
    "$defs": {
      "ComponentSearchResult": {
        "properties": {
          "componentId": {
            "title": "Componentid",
            "type": "string"
          },
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Name"
          },
          "score": {
            "title": "Score",
            "type": "number"
          }
        },
        "required": [
          "componentId",
          "score"
        ],
        "title": "ComponentSearchResult",
        "type": "object"
      }
    },
    "properties": {
      "results": {
        "items": {
          "$ref": "#/$defs/ComponentSearchResult"
        },
        "title": "Results",
        "type": "array"
      }
    },
    "required": [
      "results"
    ],
    "title": "ComponentSearchResponse",
    "type": "object"
  },
  "DatasheetExtractRequest": {
    "$defs": {
      "SymbolPin": {
        "properties": {
          "pinNumber": {
            "title": "Pinnumber",
            "type": "string"
          },
          "pinName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Pinname"
          },
          "electricalType": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Electricaltype"
          }
        },
        "required": [
          "pinNumber"
        ],
        "title": "SymbolPin",
        "type": "object"
      }
    },
    "properties": {
      "kind": {
        "enum": [
          "pins",
          "facts"
        ],
        "title": "Kind",
        "type": "string"
      },
      "workspaceId": {
        "title": "Workspaceid",
        "type": "string"
      },
      "sha256": {
        "anyOf": [
          {
            "pattern": "^[0-9a-f]{64}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Sha256"
      },
      "mpn": {
        "default": "",
        "title": "Mpn",
        "type": "string"
      },
      "componentId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Componentid"
      },
      "designId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Designid"
      },
      "symbolPins": {
        "anyOf": [
          {
            "items": {
              "$ref": "#/$defs/SymbolPin"
            },
            "type": "array"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Symbolpins"
      }
    },
    "required": [
      "kind",
      "workspaceId"
    ],
    "title": "DatasheetExtractRequest",
    "type": "object"
  },
  "DatasheetExtractResponse": {
    "$defs": {
      "AbsMax": {
        "properties": {
          "vddMaxV": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Vddmaxv"
          },
          "tjMaxC": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Tjmaxc"
          }
        },
        "title": "AbsMax",
        "type": "object"
      },
      "FactsPayload": {
        "properties": {
          "package": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Package"
          },
          "absMax": {
            "anyOf": [
              {
                "$ref": "#/$defs/AbsMax"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "operating": {
            "anyOf": [
              {
                "$ref": "#/$defs/Operating"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "perPin": {
            "items": {
              "$ref": "#/$defs/PerPin"
            },
            "title": "Perpin",
            "type": "array"
          },
          "thermal": {
            "anyOf": [
              {
                "$ref": "#/$defs/Thermal"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "title": "FactsPayload",
        "type": "object"
      },
      "Operating": {
        "properties": {
          "vddMinV": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Vddminv"
          },
          "vddMaxV": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Vddmaxv"
          },
          "tempMinC": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Tempminc"
          },
          "tempMaxC": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Tempmaxc"
          }
        },
        "title": "Operating",
        "type": "object"
      },
      "PerPin": {
        "properties": {
          "pinNumber": {
            "title": "Pinnumber",
            "type": "string"
          },
          "maxCurrentMa": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Maxcurrentma"
          },
          "fiveVoltTolerant": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Fivevolttolerant"
          }
        },
        "required": [
          "pinNumber"
        ],
        "title": "PerPin",
        "type": "object"
      },
      "PinSuggestion": {
        "properties": {
          "pinNumber": {
            "title": "Pinnumber",
            "type": "string"
          },
          "pinName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Pinname"
          },
          "signalType": {
            "default": "unknown",
            "enum": [
              "digital",
              "analog",
              "power",
              "ground",
              "clock",
              "rf",
              "diff-pair",
              "high-speed",
              "mixed",
              "unknown"
            ],
            "title": "Signaltype",
            "type": "string"
          },
          "confidence": {
            "default": 0,
            "maximum": 1,
            "minimum": 0,
            "title": "Confidence",
            "type": "number"
          },
          "rationale": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Rationale"
          },
          "page": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Page"
          }
        },
        "required": [
          "pinNumber"
        ],
        "title": "PinSuggestion",
        "type": "object"
      },
      "Thermal": {
        "properties": {
          "thetaJaCPerW": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Thetajacperw"
          }
        },
        "title": "Thermal",
        "type": "object"
      }
    },
    "properties": {
      "status": {
        "enum": [
          "ready",
          "preparing"
        ],
        "title": "Status",
        "type": "string"
      },
      "modelVersion": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Modelversion"
      },
      "sha256": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Sha256"
      },
      "pins": {
        "anyOf": [
          {
            "items": {
              "$ref": "#/$defs/PinSuggestion"
            },
            "type": "array"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Pins"
      },
      "facts": {
        "anyOf": [
          {
            "$ref": "#/$defs/FactsPayload"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "sha256s": {
        "items": {
          "type": "string"
        },
        "title": "Sha256S",
        "type": "array"
      },
      "streamUrl": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Streamurl"
      }
    },
    "required": [
      "status"
    ],
    "title": "DatasheetExtractResponse",
    "type": "object"
  },
  "DatasheetSearchRequest": {
    "properties": {
      "query": {
        "minLength": 1,
        "title": "Query",
        "type": "string"
      },
      "workspaceId": {
        "title": "Workspaceid",
        "type": "string"
      },
      "scope": {
        "default": "design",
        "enum": [
          "design",
          "library"
        ],
        "title": "Scope",
        "type": "string"
      },
      "componentId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Componentid"
      },
      "designId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Designid"
      },
      "mpn": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Mpn"
      },
      "sha256s": {
        "items": {
          "type": "string"
        },
        "title": "Sha256S",
        "type": "array"
      },
      "count": {
        "default": 8,
        "maximum": 20,
        "minimum": 1,
        "title": "Count",
        "type": "integer"
      },
      "includeOlderRevisions": {
        "default": false,
        "title": "Includeolderrevisions",
        "type": "boolean"
      }
    },
    "required": [
      "query",
      "workspaceId"
    ],
    "title": "DatasheetSearchRequest",
    "type": "object"
  },
  "DatasheetSearchResponse": {
    "$defs": {
      "SearchExcerpt": {
        "properties": {
          "sha256": {
            "title": "Sha256",
            "type": "string"
          },
          "page": {
            "title": "Page",
            "type": "integer"
          },
          "ord": {
            "title": "Ord",
            "type": "integer"
          },
          "content": {
            "title": "Content",
            "type": "string"
          },
          "score": {
            "title": "Score",
            "type": "number"
          },
          "mpn": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Mpn"
          }
        },
        "required": [
          "sha256",
          "page",
          "ord",
          "content",
          "score"
        ],
        "title": "SearchExcerpt",
        "type": "object"
      },
      "SourceRef": {
        "description": "AiSourceRef parity (ai-core source-ref.ts): id required, kind 'file'.",
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "kind": {
            "default": "file",
            "title": "Kind",
            "type": "string"
          },
          "label": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Label"
          },
          "refId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Refid"
          },
          "path": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Path"
          },
          "metadata": {
            "anyOf": [
              {
                "additionalProperties": true,
                "type": "object"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Metadata"
          }
        },
        "required": [
          "id"
        ],
        "title": "SourceRef",
        "type": "object"
      }
    },
    "properties": {
      "status": {
        "enum": [
          "ready",
          "preparing"
        ],
        "title": "Status",
        "type": "string"
      },
      "excerpts": {
        "items": {
          "$ref": "#/$defs/SearchExcerpt"
        },
        "title": "Excerpts",
        "type": "array"
      },
      "sources": {
        "items": {
          "$ref": "#/$defs/SourceRef"
        },
        "title": "Sources",
        "type": "array"
      },
      "sha256s": {
        "items": {
          "type": "string"
        },
        "title": "Sha256S",
        "type": "array"
      },
      "preparingSha256s": {
        "items": {
          "type": "string"
        },
        "title": "Preparingsha256S",
        "type": "array"
      },
      "failedSha256s": {
        "items": {
          "type": "string"
        },
        "title": "Failedsha256S",
        "type": "array"
      },
      "streamUrl": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Streamurl"
      }
    },
    "required": [
      "status"
    ],
    "title": "DatasheetSearchResponse",
    "type": "object"
  },
  "ErrorBody": {
    "$defs": {
      "ErrorDetail": {
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "sha256": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Sha256"
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "ErrorDetail",
        "type": "object"
      }
    },
    "properties": {
      "error": {
        "$ref": "#/$defs/ErrorDetail"
      }
    },
    "required": [
      "error"
    ],
    "title": "ErrorBody",
    "type": "object"
  },
  "LlmModelEntry": {
    "properties": {
      "id": {
        "title": "Id",
        "type": "string"
      },
      "object": {
        "const": "model",
        "default": "model",
        "title": "Object",
        "type": "string"
      },
      "owned_by": {
        "default": "openpcb",
        "title": "Owned By",
        "type": "string"
      },
      "default": {
        "type": "boolean",
        "default": false,
        "title": "Default"
      }
    },
    "required": [
      "id"
    ],
    "title": "LlmModelEntry",
    "type": "object"
  },
  "LlmModelList": {
    "$defs": {
      "LlmModelEntry": {
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "object": {
            "const": "model",
            "default": "model",
            "title": "Object",
            "type": "string"
          },
          "owned_by": {
            "default": "openpcb",
            "title": "Owned By",
            "type": "string"
          },
          "default": {
            "type": "boolean",
            "default": false,
            "title": "Default"
          }
        },
        "required": [
          "id"
        ],
        "title": "LlmModelEntry",
        "type": "object"
      }
    },
    "properties": {
      "object": {
        "const": "list",
        "default": "list",
        "title": "Object",
        "type": "string"
      },
      "data": {
        "items": {
          "$ref": "#/$defs/LlmModelEntry"
        },
        "title": "Data",
        "type": "array"
      }
    },
    "required": [
      "data"
    ],
    "title": "LlmModelList",
    "type": "object"
  },
  "MemoryGetBlocksRequest": {
    "properties": {
      "workspaceId": {
        "title": "Workspaceid",
        "type": "string"
      },
      "designId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Designid"
      },
      "runKind": {
        "default": "",
        "title": "Runkind",
        "type": "string"
      },
      "refTerms": {
        "items": {
          "type": "string"
        },
        "maxItems": 200,
        "title": "Refterms",
        "type": "array"
      },
      "maxTokens": {
        "default": 16000,
        "maximum": 64000,
        "minimum": 1,
        "title": "Maxtokens",
        "type": "integer"
      }
    },
    "required": [
      "workspaceId"
    ],
    "title": "MemoryGetBlocksRequest",
    "type": "object"
  },
  "MemoryGetBlocksResponse": {
    "$defs": {
      "PromptContextBlock": {
        "description": "AiPromptContextBlock parity (memory/selection.to_blocks output).",
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "title": {
            "title": "Title",
            "type": "string"
          },
          "content": {
            "title": "Content",
            "type": "string"
          },
          "priority": {
            "title": "Priority",
            "type": "integer"
          }
        },
        "required": [
          "id",
          "title",
          "content",
          "priority"
        ],
        "title": "PromptContextBlock",
        "type": "object"
      }
    },
    "properties": {
      "blocks": {
        "items": {
          "$ref": "#/$defs/PromptContextBlock"
        },
        "title": "Blocks",
        "type": "array"
      }
    },
    "required": [
      "blocks"
    ],
    "title": "MemoryGetBlocksResponse",
    "type": "object"
  },
  "MemoryRecordRequest": {
    "properties": {
      "workspaceId": {
        "title": "Workspaceid",
        "type": "string"
      },
      "designId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Designid"
      },
      "key": {
        "maxLength": 200,
        "minLength": 1,
        "title": "Key",
        "type": "string"
      },
      "value": {
        "default": null,
        "title": "Value"
      },
      "source": {
        "default": "agent",
        "enum": [
          "user",
          "agent"
        ],
        "title": "Source",
        "type": "string"
      }
    },
    "required": [
      "workspaceId",
      "key"
    ],
    "title": "MemoryRecordRequest",
    "type": "object"
  },
  "MemoryRecordResponse": {
    "properties": {
      "id": {
        "title": "Id",
        "type": "string"
      },
      "scope": {
        "enum": [
          "org",
          "design"
        ],
        "title": "Scope",
        "type": "string"
      },
      "key": {
        "title": "Key",
        "type": "string"
      }
    },
    "required": [
      "id",
      "scope",
      "key"
    ],
    "title": "MemoryRecordResponse",
    "type": "object"
  },
  "RefRequest": {
    "properties": {
      "kind": {
        "enum": [
          "component",
          "design"
        ],
        "title": "Kind",
        "type": "string"
      },
      "workspaceId": {
        "title": "Workspaceid",
        "type": "string"
      },
      "id": {
        "title": "Id",
        "type": "string"
      },
      "sha256": {
        "pattern": "^[0-9a-f]{64}$",
        "title": "Sha256",
        "type": "string"
      },
      "primary": {
        "default": false,
        "title": "Primary",
        "type": "boolean"
      }
    },
    "required": [
      "kind",
      "workspaceId",
      "id",
      "sha256"
    ],
    "title": "RefRequest",
    "type": "object"
  },
  "RegisterRequest": {
    "$defs": {
      "OwnerRef": {
        "properties": {
          "kind": {
            "enum": [
              "component",
              "design"
            ],
            "title": "Kind",
            "type": "string"
          },
          "workspaceId": {
            "title": "Workspaceid",
            "type": "string"
          },
          "id": {
            "title": "Id",
            "type": "string"
          },
          "primary": {
            "default": false,
            "title": "Primary",
            "type": "boolean"
          }
        },
        "required": [
          "kind",
          "workspaceId",
          "id"
        ],
        "title": "OwnerRef",
        "type": "object"
      },
      "StorageRef": {
        "properties": {
          "bucket": {
            "title": "Bucket",
            "type": "string"
          },
          "key": {
            "title": "Key",
            "type": "string"
          }
        },
        "required": [
          "bucket",
          "key"
        ],
        "title": "StorageRef",
        "type": "object"
      }
    },
    "properties": {
      "sha256": {
        "pattern": "^[0-9a-f]{64}$",
        "title": "Sha256",
        "type": "string"
      },
      "byteSize": {
        "exclusiveMinimum": 0,
        "title": "Bytesize",
        "type": "integer"
      },
      "source": {
        "enum": [
          "user-upload",
          "vendor-fetch",
          "core-authored"
        ],
        "title": "Source",
        "type": "string"
      },
      "visibility": {
        "enum": [
          "global",
          "private"
        ],
        "title": "Visibility",
        "type": "string"
      },
      "storage": {
        "anyOf": [
          {
            "$ref": "#/$defs/StorageRef"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "sourceUrl": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Sourceurl"
      },
      "mpn": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Mpn"
      },
      "manufacturer": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Manufacturer"
      },
      "title": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Title"
      },
      "license": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "License"
      },
      "owner": {
        "anyOf": [
          {
            "$ref": "#/$defs/OwnerRef"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      }
    },
    "required": [
      "sha256",
      "byteSize",
      "source",
      "visibility"
    ],
    "title": "RegisterRequest",
    "type": "object"
  },
  "RegisterResponse": {
    "properties": {
      "sha256": {
        "title": "Sha256",
        "type": "string"
      },
      "status": {
        "enum": [
          "registered",
          "queued",
          "fetching",
          "extracting",
          "embedding",
          "done",
          "failed"
        ],
        "title": "Status",
        "type": "string"
      },
      "alreadyIngested": {
        "title": "Alreadyingested",
        "type": "boolean"
      }
    },
    "required": [
      "sha256",
      "status",
      "alreadyIngested"
    ],
    "title": "RegisterResponse",
    "type": "object"
  },
  "ToolManifest": {
    "$defs": {
      "ToolManifestEntry": {
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "version": {
            "title": "Version",
            "type": "string"
          },
          "inputSchemaRef": {
            "title": "Inputschemaref",
            "type": "string"
          },
          "outputSchemaRef": {
            "title": "Outputschemaref",
            "type": "string"
          },
          "pricing": {
            "$ref": "#/$defs/ToolPricing"
          },
          "durationClass": {
            "enum": [
              "fast",
              "slow"
            ],
            "title": "Durationclass",
            "type": "string"
          },
          "authScope": {
            "enum": [
              "pro",
              "workspace-viewer",
              "workspace-editor"
            ],
            "title": "Authscope",
            "type": "string"
          },
          "minClientVersion": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Minclientversion"
          }
        },
        "required": [
          "name",
          "version",
          "inputSchemaRef",
          "outputSchemaRef",
          "pricing",
          "durationClass",
          "authScope"
        ],
        "title": "ToolManifestEntry",
        "type": "object"
      },
      "ToolPricing": {
        "properties": {
          "unit": {
            "const": "call",
            "title": "Unit",
            "type": "string"
          },
          "credits": {
            "title": "Credits",
            "type": "number"
          }
        },
        "required": [
          "unit",
          "credits"
        ],
        "title": "ToolPricing",
        "type": "object"
      }
    },
    "properties": {
      "apiVersion": {
        "default": "v2",
        "title": "Apiversion",
        "type": "string"
      },
      "pricingVersion": {
        "title": "Pricingversion",
        "type": "string"
      },
      "tools": {
        "items": {
          "$ref": "#/$defs/ToolManifestEntry"
        },
        "title": "Tools",
        "type": "array"
      }
    },
    "required": [
      "pricingVersion",
      "tools"
    ],
    "title": "ToolManifest",
    "type": "object"
  },
  "ToolManifestEntry": {
    "$defs": {
      "ToolPricing": {
        "properties": {
          "unit": {
            "const": "call",
            "title": "Unit",
            "type": "string"
          },
          "credits": {
            "title": "Credits",
            "type": "number"
          }
        },
        "required": [
          "unit",
          "credits"
        ],
        "title": "ToolPricing",
        "type": "object"
      }
    },
    "properties": {
      "name": {
        "title": "Name",
        "type": "string"
      },
      "version": {
        "title": "Version",
        "type": "string"
      },
      "inputSchemaRef": {
        "title": "Inputschemaref",
        "type": "string"
      },
      "outputSchemaRef": {
        "title": "Outputschemaref",
        "type": "string"
      },
      "pricing": {
        "$ref": "#/$defs/ToolPricing"
      },
      "durationClass": {
        "enum": [
          "fast",
          "slow"
        ],
        "title": "Durationclass",
        "type": "string"
      },
      "authScope": {
        "enum": [
          "pro",
          "workspace-viewer",
          "workspace-editor"
        ],
        "title": "Authscope",
        "type": "string"
      },
      "minClientVersion": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Minclientversion"
      }
    },
    "required": [
      "name",
      "version",
      "inputSchemaRef",
      "outputSchemaRef",
      "pricing",
      "durationClass",
      "authScope"
    ],
    "title": "ToolManifestEntry",
    "type": "object"
  }
} as unknown as Record<
  string,
  AiJsonSchemaObject
>;
