/**
 * DXF → import edges. Decodes the entity types that make up a mechanical board
 * outline (LINE, LWPOLYLINE with bulge, ARC, CIRCLE, ELLIPSE, SPLINE, legacy
 * POLYLINE), preserving circular arcs (bulge / ARC / CIRCLE) as arc edges and
 * tessellating ellipses / splines to the shared chord tolerance. Untrusted
 * input: byte / entity / generated-segment caps guard it before and during
 * parsing. Blocks (INSERT) are not expanded — reported, not silently dropped.
 */
import DxfParser from "dxf-parser";
import type { EdgeSeg } from "../../pcb/chain-edges";
import {
  arcSegmentCount,
  MAX_CHORD_DEVIATION_MM,
} from "../../pcb/outline-geometry";

export interface DxfParseOptions {
  /** mm per DXF drawing unit. Overrides the value derived from $INSUNITS. */
  unitScaleMm?: number;
  maxBytes?: number;
  maxEntities?: number;
  /** Cap on points generated by ellipse / spline tessellation. */
  maxGeneratedSegments?: number;
}

export interface DxfParseResult {
  edges: EdgeSeg[];
  layers: string[];
  unitScaleMm: number;
  detectedUnits: string;
  diagnostics: string[];
}

const DEFAULT_MAX_BYTES = 8_000_000;
// A real board outline has at most a few hundred edges. Cap low so the
// downstream O(n²) loop-assembly + self-intersection validation stay bounded on
// untrusted input (a giant DXF can't wedge the single backend thread).
const DEFAULT_MAX_ENTITIES = 5_000;
const DEFAULT_MAX_GENERATED = 50_000;

/** $INSUNITS → mm-per-unit + label (subset covering the common cases). */
const INSUNITS_MM: Record<number, { scale: number; label: string }> = {
  0: { scale: 1, label: "unitless (assumed mm)" },
  1: { scale: 25.4, label: "inch" },
  2: { scale: 304.8, label: "foot" },
  4: { scale: 1, label: "mm" },
  5: { scale: 10, label: "cm" },
  6: { scale: 1000, label: "m" },
  8: { scale: 0.0000254, label: "microinch" },
  9: { scale: 0.0254, label: "mil" },
  10: { scale: 914.4, label: "yard" },
  11: { scale: 1e-7, label: "angstrom" },
  12: { scale: 1e-6, label: "nanometer" },
  13: { scale: 0.001, label: "micron" },
  14: { scale: 100, label: "decimeter" },
};

export class DxfImportError extends Error {}

export function parseDxfToEdges(
  dxfText: string,
  opts: DxfParseOptions = {},
): DxfParseResult {
  const maxBytes = opts.maxBytes ?? DEFAULT_MAX_BYTES;
  if (dxfText.length > maxBytes) {
    throw new DxfImportError(
      `DXF is too large (${dxfText.length} > ${maxBytes} bytes)`,
    );
  }

  let dxf;
  try {
    dxf = new DxfParser().parseSync(dxfText);
  } catch (err) {
    throw new DxfImportError(
      `could not parse DXF: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  if (!dxf || !Array.isArray(dxf.entities)) {
    throw new DxfImportError("DXF contains no entities");
  }

  const maxEntities = opts.maxEntities ?? DEFAULT_MAX_ENTITIES;
  if (dxf.entities.length > maxEntities) {
    throw new DxfImportError(
      `DXF has too many entities (${dxf.entities.length} > ${maxEntities})`,
    );
  }

  const insunits = Number(dxf.header?.["$INSUNITS"] ?? 0);
  const unit = INSUNITS_MM[insunits] ?? { scale: 1, label: `unknown (code ${insunits})` };
  const unitScaleMm = opts.unitScaleMm ?? unit.scale;

  const diagnostics: string[] = [];
  const layers = new Set<string>();
  const edges: EdgeSeg[] = [];
  const maxGenerated = opts.maxGeneratedSegments ?? DEFAULT_MAX_GENERATED;
  let generated = 0;
  const budget = (n: number): void => {
    generated += n;
    if (generated > maxGenerated) {
      throw new DxfImportError(
        `DXF tessellation exceeded ${maxGenerated} generated segments`,
      );
    }
  };

  const s = unitScaleMm;
  const pt = (x: number, y: number) => ({ x: x * s, y: y * s });

  for (const ent of dxf.entities) {
    if (ent.layer) layers.add(ent.layer);
    switch (ent.type) {
      case "LINE": {
        const v = (ent as any).vertices as Array<{ x: number; y: number }>;
        if (v?.length >= 2) {
          edges.push({ from: pt(v[0]!.x, v[0]!.y), to: pt(v[1]!.x, v[1]!.y) });
        }
        break;
      }
      case "LWPOLYLINE":
      case "POLYLINE": {
        pushPolyline(ent as any, edges, pt, diagnostics);
        break;
      }
      case "ARC": {
        const a = ent as any;
        edges.push(arcEntityToEdge(a.center, a.radius, a.startAngle, a.endAngle, pt));
        break;
      }
      case "CIRCLE": {
        const c = ent as any;
        // Split into four CCW quarter-arcs: the assembler closes them into a
        // loop, and a contour needs >= 3 segments (two semicircles wouldn't do).
        const cen = pt(c.center.x, c.center.y);
        const r = c.radius * s;
        const q = [
          { x: cen.x + r, y: cen.y },
          { x: cen.x, y: cen.y + r },
          { x: cen.x - r, y: cen.y },
          { x: cen.x, y: cen.y - r },
        ];
        for (let i = 0; i < 4; i += 1) {
          edges.push({
            from: q[i]!,
            to: q[(i + 1) % 4]!,
            arc: { centerMm: cen, cw: false },
          });
        }
        break;
      }
      case "ELLIPSE": {
        budget(pushEllipse(ent as any, edges, pt, s));
        break;
      }
      case "SPLINE": {
        budget(pushSpline(ent as any, edges, pt, diagnostics));
        break;
      }
      case "INSERT":
        diagnostics.push("skipped a block reference (INSERT) — not expanded");
        break;
      default:
        break;
    }
  }

  return {
    edges,
    layers: [...layers],
    unitScaleMm,
    detectedUnits: unit.label,
    diagnostics,
  };
}

type PtFn = (x: number, y: number) => { x: number; y: number };

/** DXF bulge (tan of ¼ the included angle) → arc center + winding. */
function bulgeToArc(
  p0: { x: number; y: number },
  p1: { x: number; y: number },
  bulge: number,
): { centerMm: { x: number; y: number }; cw: boolean } {
  const cot = (1 / bulge - bulge) / 2;
  const cx = (p0.x + p1.x) / 2 - (cot * (p1.y - p0.y)) / 2;
  const cy = (p0.y + p1.y) / 2 + (cot * (p1.x - p0.x)) / 2;
  return { centerMm: { x: cx, y: cy }, cw: bulge < 0 };
}

function pushPolyline(
  ent: { vertices?: Array<{ x: number; y: number; bulge?: number }>; shape?: boolean },
  edges: EdgeSeg[],
  pt: PtFn,
  diagnostics: string[],
): void {
  const verts = ent.vertices ?? [];
  if (verts.length < 2) return;
  const closed = ent.shape === true;
  const n = verts.length;
  const limit = closed ? n : n - 1;
  for (let i = 0; i < limit; i += 1) {
    const a = verts[i]!;
    const b = verts[(i + 1) % n]!;
    const from = pt(a.x, a.y);
    const to = pt(b.x, b.y);
    if (a.bulge && Math.abs(a.bulge) > 1e-9) {
      edges.push({ from, to, arc: bulgeToArc(from, to, a.bulge) });
    } else {
      edges.push({ from, to });
    }
  }
  if (!closed) {
    diagnostics.push("an open polyline was imported as a chain (not closed)");
  }
}

function arcEntityToEdge(
  center: { x: number; y: number },
  radius: number,
  startRad: number,
  endRad: number,
  pt: PtFn,
): EdgeSeg {
  const cen = pt(center.x, center.y);
  const r = radius * (pt(1, 0).x - pt(0, 0).x); // radius in scaled units
  // dxf-parser already returns ARC group codes 50/51 in radians — use directly.
  const from = {
    x: cen.x + r * Math.cos(startRad),
    y: cen.y + r * Math.sin(startRad),
  };
  const to = {
    x: cen.x + r * Math.cos(endRad),
    y: cen.y + r * Math.sin(endRad),
  };
  // DXF ARC sweeps counter-clockwise from start to end.
  return { from, to, arc: { centerMm: cen, cw: false } };
}

function pushEllipse(
  ent: {
    center: { x: number; y: number };
    majorAxisEndPoint: { x: number; y: number };
    axisRatio: number;
    startAngle: number;
    endAngle: number;
  },
  edges: EdgeSeg[],
  pt: PtFn,
  scale: number,
): number {
  const cen = pt(ent.center.x, ent.center.y);
  const majX = ent.majorAxisEndPoint.x * scale;
  const majY = ent.majorAxisEndPoint.y * scale;
  const majLen = Math.hypot(majX, majY);
  const minLen = majLen * ent.axisRatio;
  const rot = Math.atan2(majY, majX);
  let sweep = ent.endAngle - ent.startAngle;
  if (Math.abs(sweep) < 1e-9) sweep = Math.PI * 2; // full ellipse
  // DXF ellipse params sweep CCW and may wrap through 2π; keep the sweep
  // positive so we tessellate the intended side (not its complement).
  while (sweep < 0) sweep += Math.PI * 2;
  const steps = arcSegmentCount(Math.max(majLen, minLen), sweep);
  const cos = Math.cos(rot);
  const sin = Math.sin(rot);
  const at = (t: number) => {
    const lx = majLen * Math.cos(t);
    const ly = minLen * Math.sin(t);
    return { x: cen.x + lx * cos - ly * sin, y: cen.y + lx * sin + ly * cos };
  };
  let prev = at(ent.startAngle);
  for (let i = 1; i <= steps; i += 1) {
    const cur = at(ent.startAngle + (sweep * i) / steps);
    edges.push({ from: prev, to: cur });
    prev = cur;
  }
  return steps;
}

function pushSpline(
  ent: { fitPoints?: Array<{ x: number; y: number }>; controlPoints?: Array<{ x: number; y: number }>; closed?: boolean },
  edges: EdgeSeg[],
  pt: PtFn,
  diagnostics: string[],
): number {
  const raw = ent.fitPoints?.length ? ent.fitPoints : ent.controlPoints ?? [];
  if (raw.length < 2) return 0;
  if (!ent.fitPoints?.length) {
    diagnostics.push("a spline was approximated by its control polygon");
  } else {
    diagnostics.push("a spline was imported as its fit-point polyline");
  }
  const pts = raw.map((p) => pt(p.x, p.y));
  const n = pts.length;
  const limit = ent.closed ? n : n - 1;
  for (let i = 0; i < limit; i += 1) {
    edges.push({ from: pts[i]!, to: pts[(i + 1) % n]! });
  }
  return limit;
}
