#!/usr/bin/env bun
// Emits a runtime {schemaName -> JSON Schema} map from the vendored cloud-copilot
// tool schemas in @openpcb/contracts, so remoteTool() can resolve a manifest
// entry's `inputSchemaRef` to the actual input schema. ai-core needs the real
// schema for model-arg advertisement + Ajv validation, but @openpcb/contracts
// only `exports` dist/, so the raw schemas/copilot/*.json are not importable —
// this vendors them into a committed generated module instead.
//
//   bun scripts/gen-copilot-tool-schemas.ts           # regenerate in place
//   bun scripts/gen-copilot-tool-schemas.ts --check    # diff-only, exit 1 on drift
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), "..");
const SCHEMA_DIR = path.join(
  ROOT,
  "node_modules/@openpcb/contracts/schemas/copilot",
);
const OUTPUT_PATH = path.join(
  ROOT,
  "src/modules/assistant/backend/cloud/copilot-tool-schemas.generated.ts",
);

let schemaCount = 0;

async function build(): Promise<string> {
  const files = (await fs.readdir(SCHEMA_DIR))
    .filter((f) => f.endsWith(".schema.json"))
    .sort();
  schemaCount = files.length;
  const map: Record<string, unknown> = {};
  for (const file of files) {
    const name = file.replace(/\.schema\.json$/, "");
    map[name] = JSON.parse(await fs.readFile(path.join(SCHEMA_DIR, file), "utf8"));
  }
  const body = JSON.stringify(map, null, 2);
  return `// AUTO-GENERATED by scripts/gen-copilot-tool-schemas.ts — do not edit.
// Runtime map of cloud-copilot tool JSON schemas (keyed by schema name), vendored
// from @openpcb/contracts/schemas/copilot. remoteTool() resolves a manifest
// entry's inputSchemaRef against this map. Regenerate: npm run gen:copilot-schemas.
import type { AiJsonSchemaObject } from "@openpcb/ai-core";

export const COPILOT_TOOL_SCHEMAS = ${body} as unknown as Record<
  string,
  AiJsonSchemaObject
>;
`;
}

async function main(): Promise<void> {
  const out = await build();
  if (process.argv.includes("--check")) {
    const existing = await fs.readFile(OUTPUT_PATH, "utf8").catch(() => "");
    if (existing !== out) {
      console.error(
        "copilot-tool-schemas.generated.ts is stale — run npm run gen:copilot-schemas",
      );
      process.exit(1);
    }
    console.log("copilot-tool-schemas.generated.ts up to date");
    return;
  }
  await fs.writeFile(OUTPUT_PATH, out);
  console.log(`wrote ${path.relative(ROOT, OUTPUT_PATH)} (${schemaCount} schemas)`);
}

void main();
